### ISSUE TITLE
[SURE-7557] user-group-psp-policy does not work in audit mode if container image runs as user 0

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/user-group-psp-policy#75] opened 2024-02-06 13:40 UTC
### Issue description:
Customer is using the user-group-psp-policy (https://github.com/kubewarden/user-group-psp-policy) from Kubewarden to ensure containers do not run as root. Image built with root (userid 0) not getting reported in policy server logs when policy is in monitor mode. However, image get denied while using protect mode without any issues. Customer requires similar message to be available in the PolicyReport object too.

### Business impact:
Customer expect the policy to also report non-compliance in audit mode, to be able to provide a report for developers on what to change before enforcing the policy.

### Repro steps:

Install do-not-run-as-root clusteradmissionpolicy in Kube-warden(latest version) in monitor mode
Apply a deployment using an image with root user (eg: registry.suse.com/suse/sle15:latest) without any securityContext
You can see its getting allowed, but no logs specific to the deployment(other than a POST request) are showing in either policy server logs or in policy reports.
But if you deploy the same image with securityContext(runAsUser: 0), you can see the invalid user message in the policy server logs. Policyreports still shows as pass

### Workaround:
Is workararound available and implemented? no

### Actual behavior:
No audit message is available (in monitor mode) in the policy server logs or policy reports when the image(builtin root user) is deployed

### Expected behavior:
Proper audit messages should be available in policy server logs and policy reports when policy is in monitor mode

Files, logs, traces:

Actually message in policy server logs:
~~~
2024-01-31T16:56:36.480375Z  INFO request{method=POST uri=/validate/clusterwide-do-not-run-as-root?timeout=10s version=HTTP/1.1}:validation{host="policy-server-default-7d89cdb68d-wnf7h" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="" namespace="mykb" operation="CREATE" request_uid="5b0355d4-0e9b-4ffd-bd50-7227418b4e1e" resource="pods" resource_group="" resource_version="v1" subresource=""}: policy_server::api::service: policy evaluation (monitor mode) policy_id="clusterwide-do-not-run-as-root" allowed_to_mutate=true response="AdmissionResponse { uid: \"5b0355d4-0e9b-4ffd-bd50-7227418b4e1e\", allowed: true, patch_type: Some(\"JSONPatch\"), patch: Some(\"W3sib3AiOiJyZW1vdmUiLCJwYXRoIjoiL21ldGFkYXRhL2NyZWF0aW9uVGltZXN0YW1wIn0seyJvcCI6ImFkZCIsInBhdGgiOiIvc3BlYy9jb250YWluZXJzLzAvc2VjdXJpdHlDb250ZXh0IiwidmFsdWUiOnsicnVuQXNOb25Sb290Ijp0cnVlfX0seyJvcCI6ImFkZCIsInBhdGgiOiIvc3BlYy9zZWN1cml0eUNvbnRleHQvcnVuQXNOb25Sb290IiwidmFsdWUiOnRydWV9XQ==\"), status: None, audit_annotations: None, warnings: None }"
2024-01-31T16:56:36.482112Z  INFO request{method=POST uri=/validate/clusterwide-do-not-run-as-root?timeout=10s version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=3 ms status=200
~~~

Proper message while using securityContext with userid hardcoded:
~~~
2024-01-31T16:20:49.998019Z  INFO request{method=POST uri=/validate/clusterwide-do-not-run-as-root?timeout=10s version=HTTP/1.1}:validation{host="policy-server-default-8479cb6fd4-9mczh" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="" namespace="mykb" operation="CREATE" request_uid="de5053e2-d704-4c7c-81ea-4299524ff408" resource="pods" resource_group="" resource_version="v1" subresource=""}: policy_server::api::service: policy evaluation (monitor mode) policy_id="clusterwide-do-not-run-as-root" allowed_to_mutate=true response="AdmissionResponse { uid: \"de5053e2-d704-4c7c-81ea-4299524ff408\", allowed: false, patch_type: None, patch: None, status: Some(AdmissionResponseStatus { message: Some(\"Invalid user ID: cannot run container with root ID (0)\"), code: None }), audit_annotations: None, warnings: None }"
2024-01-31T16:20:49.999487Z  INFO request{method=POST uri=/validate/clusterwide-do-not-run-as-root?timeout=10s version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=3 ms status=200
~~~

**Comment by jvanz** [comment] 2024-02-07 16:22
This is not a bug. The policy is a replacement for the old Kubernetes PSP. As the PSPs, this policy check only the security context of the containers. It does not inspect the container image. That's why when the user does not define the securitu context the request is allowed with no complains. Therefore, if we want to inspect the container image we need to implement this new functionality. That will required the [new capability](https://github.com/orgs/kubewarden/projects/6/views/1?pane=issue&itemId=50747254) to fetch the container image manifest which is not available right now. 

For now, **maybe** a workaround is to set the `overwrite` to true in the policy settings. This is not exactly what the user wants but at least the policy will mutate the request when it misses the security context settings. Which should be visible as a mutated request in the logs and/or tracing. 

If the user still wants this new feature, let us know, we can prioritize it as such. Thanks!

**Comment by jvanz** [comment] 2024-02-07 16:23
Moved this to block until we get a feedback from the user.

**Comment by jvanz** [comment] 2024-02-16 18:50
Talking with user in other communication channels. Waiting for a response. Moving to block

**Comment by jvanz** [comment] 2024-02-26 14:37
The error message reported by the user came from kubelet. Which means that the policy is working as expected. There is no bug in the policy. Moving to block again until we got a feedback from the explanation that I have sent to them.

**Comment by flavio** [comment] 2024-03-08 14:38
Closing, no answer from the user

**Comment by kkaempf** [comment] 2024-03-14 16:07
SURE-7557 is a feature request now, reopening for evaluation.

**Comment by jvanz** [comment] 2024-05-29 18:26
Moving this to block until we get the new host capability

**Closed** 2024-06-28 18:27 UTC
Labels: kind/enhancement, JIRA
